import { useObservable } from "micro-observables";
import "./library.css";
import { useServices } from "@/domain/core/services";
import { ThumbsUp } from "lucide-react";
import { ArtWork } from "@/domain/services/types";
import { TwitterShareButton } from "react-share";
import { BsTwitterX } from "react-icons/bs";
import ExpandableText from "./Expandable";

export const Leaderboard = () => {
  const { voteService } = useServices();
  const collections = useObservable(voteService.collections);
  console.log({ collections });

  collections?.sort((a, b) => b.voteCount - a.voteCount);

  const text = `📢 Help me win 2️⃣0️⃣0️⃣ SUI🌊
 
✅Vote for my collection generated by JarJar AI oracle🤖

❤️ Vote here: `;

  return (
    <>
      <div>
        <h1 className="text-center text-black mb-8 text-3xl">Leaderboard</h1>
        {collections?.map((collection) => (
          <div
            className="text-black nft-box"
            key={collection.id}
            id={collection.id.toString()}
          >
            <div className="justify-between mb-2 flex-row">
              <div className="mt-2">
                <span className="font-bold mr-3">Model: </span>{" "}
                {collection.model_name}
                <span className="font-bold ml-3 mr-3">id: </span>{" "}
                {collection.id}
              </div>
            </div>
            <div>
              <span className="font-bold">Prompt: </span>
              <ExpandableText text={collection.prompt} />
              {/* {collection.prompt} */}
            </div>
            <NftsByPromptAndModel collection={collection} />
            <div className="flex flex-row justify-center items-center mt-4">
              <div className="connect-wallet flex-row flex justify-center items-center mr-4">
                <TwitterShareButton
                  url={`https://jarjar.xyz/leaderboard/${collection.id}`}
                  via="JARJARxyz"
                  title={text}
                >
                  <div className="flex-row flex text-center text-xl">
                    Share on <BsTwitterX className="ml-2 mt-1" fill="#4a5568" />
                  </div>
                </TwitterShareButton>
              </div>
              <button
                className="connect-wallet flex-row flex justify-center items-center"
                onClick={async () => {
                  await voteService.submitVote(collection.id);
                  await voteService.getCollectionsWithUserVote();
                }}
              >
                <ThumbsUp fill={collection.userVoted ? "#4a5568" : "#e0e5ec"} />{" "}
                <span className="ml-2 text-bold text-xl">
                  {collection.voteCount}
                </span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </>
  );
};

const NftsByPromptAndModel = ({ collection }: { collection: ArtWork }) => {
  return (
    <div className="photo-library">
      {collection.images?.map((image) => (
        <a key={image} className="photo-item">
          <img src={image} alt="Square Photo 1" />
        </a>
      ))}
    </div>
  );
};
