import {
  ConnectButton,
  SuiClientProvider,
  WalletProvider,
} from "@mysten/dapp-kit";
import { Box, Flex, Heading } from "@radix-ui/themes";
import { getFullnodeUrl } from "@mysten/sui/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createNetworkConfig } from "@mysten/dapp-kit";
import { Nft } from "./Nft";
import "./app.css";

const queryClient = new QueryClient();

const { networkConfig } = createNetworkConfig({
  localnet: { url: getFullnodeUrl("localnet") },
  devnet: { url: getFullnodeUrl("devnet") },
  testnet: { url: getFullnodeUrl("testnet") },
  mainnet: { url: getFullnodeUrl("mainnet") },
});

function App() {
  console.log(
    "import.meta.env.VITE_SUI_NETWORK",
    import.meta.env.VITE_SUI_NETWORK,
  );
  return (
    <QueryClientProvider client={queryClient}>
      <SuiClientProvider
        networks={networkConfig}
        defaultNetwork={import.meta.env.VITE_SUI_NETWORK}
      >
        <WalletProvider autoConnect>
          <Flex
            position="sticky"
            px="4"
            py="2"
            justify="between"
            style={{
              borderBottom: "1px solid var(--gray-a2)",
            }}
          >
            <Box>
              <Heading>
                JARJAR 1# Collection on{" "}
                <span className="text-blue-400">$SUI</span>
              </Heading>
              <Heading className="text-sm text-gray-400 mt-2">
                Generated by the first AI oracle on the $SUI blockchain
              </Heading>
            </Box>
            <Box>
              <ConnectButton />
            </Box>
          </Flex>
          <Nft />
        </WalletProvider>
      </SuiClientProvider>
    </QueryClientProvider>
  );
}

export default App;
