import { ConnectButton } from "@mysten/dapp-kit";
import { Box, Flex, Heading } from "@radix-ui/themes";
import { Nft } from "./Nft";
import "./app.css";

function App() {
  return (
    <>
      <Flex
        position="sticky"
        px="4"
        py="2"
        justify="between"
        style={{
          borderBottom: "1px solid var(--gray-a2)",
        }}
      >
        <Box>
          <Heading>
            JARJAR 1# Collection on <span className="text-blue-400">$SUI</span>
          </Heading>
          <Heading className="text-sm text-gray-400 mt-2">
            Generated by the first AI oracle on the $SUI blockchain
          </Heading>
        </Box>
        <Box>
          <ConnectButton />
        </Box>
      </Flex>
      <Nft />
    </>
  );
}

export default App;
